services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: jobboard
      POSTGRES_PASSWORD: jobboard
      POSTGRES_DB: jobboard
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
<<<<<<< HEAD
      - "5433:5432"
=======
<<<<<<< HEAD
      - "5433:5432"
=======
      - "5434:5432"
>>>>>>> 7e52a1e (resume stored into aws_s3_buckets)
>>>>>>> 379ca77 (resumes stored in aws s3 bucket)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jobboard"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg2://jobboard:jobboard@db:5432/jobboard
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 379ca77 (resumes stored in aws s3 bucket)
      - uploads_data:/app/uploads
      - ./app:/app/app

volumes:
  db_data:
  uploads_data:
<<<<<<< HEAD
=======
=======
      - ./app:/app/app

volumes:
  db_data:
>>>>>>> 7e52a1e (resume stored into aws_s3_buckets)
>>>>>>> 379ca77 (resumes stored in aws s3 bucket)
