"""add s3_key to resumes

Revision ID: 03d08e5eac38
Revises: 5a198c8a123f
Create Date: 2026-08-08 12:04:36.378012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d08e5eac38'
down_revision: Union[str, Sequence[str], None] = '5a198c8a123f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('s3_key', sa.String(length=512), nullable=False))
    op.drop_column('resumes', 'filepath')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('filepath', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.drop_column('resumes', 's3_key')
    # ### end Alembic commands ###
